# Generated by Django 4.1.2 on 2023-01-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deces',
            name='numN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.naissance'),
        ),
    ]
