# Generated by Django 4.1.2 on 2023-01-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_naissance_grand_mere_m_naissance_grand_mere_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naissance',
            name='date_naiss_mere',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='date_naiss_pere',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='grand_mere_maternel',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='grand_mere_paternel',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='grand_pere_maternel',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='grand_pere_paternel',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='lieu_naiss_mere',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='lieu_naiss_pere',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='mere',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='pere',
        ),
    ]
