# Generated by Django 4.1.2 on 2023-01-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_naissance_grand_mere_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naissance',
            name='grand_mere_m',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='grand_mere_p',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='grand_pere_m',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='grand_pere_p',
        ),
    ]
