# Generated by Django 4.1.2 on 2023-01-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_naissance_grand_mere_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naissance',
            name='merei',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mereinfo', to='app1.naissance'),
        ),
        migrations.AlterField(
            model_name='naissance',
            name='perei',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pereinfo', to='app1.naissance'),
        ),
    ]
