# Generated by Django 4.1.2 on 2023-01-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_naissance_merei_alter_naissance_perei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naissance',
            name='merei',
        ),
        migrations.RemoveField(
            model_name='naissance',
            name='perei',
        ),
    ]
