# Generated by Django 4.1.2 on 2023-01-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_naissance_merei_naissance_perei'),
    ]

    operations = [
        migrations.AddField(
            model_name='mariage',
            name='req1',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='req1info', to='app1.naissance'),
        ),
        migrations.AddField(
            model_name='mariage',
            name='req2',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='req2info', to='app1.naissance'),
        ),
        migrations.AddField(
            model_name='mariage',
            name='temoin1',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temoin1info', to='app1.naissance'),
        ),
        migrations.AddField(
            model_name='mariage',
            name='temoin2',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temoin2info', to='app1.naissance'),
        ),
    ]
