# Generated by Django 4.1.2 on 2023-01-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_mariage_req1_mariage_req2_mariage_temoin1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mariage',
            name='date_req1',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='date_req2',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='lieu_naiss_req1',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='lieu_naiss_req2',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='nom_requerant1',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='nom_requerant2',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='prenom_requerant1',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='prenom_requerant2',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='temoin_req1',
        ),
        migrations.RemoveField(
            model_name='mariage',
            name='temoin_req2',
        ),
    ]
